




----------------------------------------------------------------------------------------------------------------------------


PRAGMA foreign_keys=OFF;

INSERT INTO "RMP" VALUES(NULL,
		'libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et,',
		'at',
		'Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero.',
		'vulputate, risus a ultricies adipiscing, enim mi tempor lorem, eget',
		123,
		132,
		24,
		'sed pede nec ante blandit viverra. Donec tempus,',
		'lorem tristique aliquet. Phasellus fermentum convallis ligula. Donec',
		'fames ac turpis egestas. Fusce aliquet magna a neque. Nullam');
INSERT INTO "RMP" VALUES(NULL,
		'id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque',
		'Phasellus',
		'euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate',
		'vel est tempor bibendum. Donec felis orci, adipiscing non, luctus',
		166,
		137,
		124,
		'nisl. Maecenas malesuada fringilla est. Mauris eu turpis.',
		'iaculis aliquet diam. Sed diam lorem, auctor quis,',
		'mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus');
INSERT INTO "RMP" VALUES(NULL
		,'Nunc pulvinar arcu et pede. Nunc sed orci lobortis augue',
		'mattis.',
		'mi felis, adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras',
		'condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing',
		42,
		180,
		186,
		'consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam',
		'blandit congue. In scelerisque scelerisque dui. Suspendisse ac',
		'ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo');
INSERT INTO "RMP" VALUES(NULL,
		'In scelerisque scelerisque dui. Suspendisse ac metus vitae velit egestas',
		'magna',
		'Ut tincidunt vehicula risus. Nulla eget metus eu erat semper',
		'netus et malesuada fames ac turpis egestas. Fusce aliquet magna',
		180,
		67,
		124,
		'risus, at fringilla purus mauris a nunc. In',
		'nec ligula consectetuer rhoncus. Nullam velit dui, semper',
		'elementum, dui quis accumsan convallis, ante lectus convallis est, vitae');
INSERT INTO "RMP" VALUES(NULL,
		'odio vel est tempor bibendum. Donec felis orci, adipiscing non,',
		'sed,',
		'magna. Praesent interdum ligula eu enim. Etiam imperdiet dictum magna.',
		'metus eu erat semper rutrum. Fusce dolor quam, elementum at,',
		110,
		148,
		35,
		'urna. Nunc quis arcu vel quam dignissim pharetra.',
		'Donec egestas. Duis ac arcu. Nunc mauris. Morbi',
		'lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie.');
INSERT INTO "RMP" VALUES(NULL,
		'Integer aliquam adipiscing lacus. Ut nec urna et arcu imperdiet',
		'id,',
		'senectus et netus et malesuada fames ac turpis egestas. Aliquam',
		'magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam',
		26,
		21,
		61,
		'non quam. Pellentesque habitant morbi tristique senectus et',
		'dignissim magna a tortor. Nunc commodo auctor velit.',
		'sit amet diam eu dolor egestas rhoncus. Proin nisl sem,');
INSERT INTO "RMP" VALUES(NULL,
		'Quisque nonummy ipsum non arcu. Vivamus sit amet risus. Donec',
		'varius',
		'nulla. Donec non justo. Proin non massa non ante bibendum',
		'velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat,',
		148,
		122,
		17,
		'a, magna. Lorem ipsum dolor sit amet, consectetuer',
		'In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus.',
		'Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc');

-------------------
INSERT INTO "orden_pedido_producto" VALUES(NULL,
		'1000',
		'8',
		35,
		'06/19/12',
		'06/29/11',
		'mi, ac');
INSERT INTO "orden_pedido_producto" VALUES(NULL,
		'1004',
		'18',
		28,
		'08/26/12',
		'01/20/13',
		'mauris. Integer');
INSERT INTO "orden_pedido_producto" VALUES(NULL,
		'1005',
		'21',
		14,
		'07/15/12',
		'04/03/11',
		'tincidunt dui');
INSERT INTO "orden_pedido_producto" VALUES(NULL,
		'1005',
		'23',
		38,
		'07/09/11',
		'06/14/12',
		'Etiam gravida');
INSERT INTO "orden_pedido_producto" VALUES(NULL,
		'1005',
		'10',
		47,
		'07/09/12',
		'06/17/12',
		'Phasellus elit');
--------------------------------------

INSERT INTO "orden_produccion" VALUES(NULL,
		'aliquet, metus urna convallis erat,',
		'1004',
		14,
		'1000',
		'1005',
		'06/21/12',
		'1001',
		'12/28/10',
		'gravida. Aliquam tincidunt, nunc',
		'urna et arcu imperdiet ullamcorper.',
		'1000',
		'1002');
INSERT INTO "orden_produccion" VALUES(NULL,
		'taciti sociosqu ad litora torquent',
		'1006',
		20,
		'1003',
		'1002',
		'01/12/13',
		'1001',
		'12/29/12',
		'ridiculus mus. Proin vel',
		'sit amet ultricies sem magna','1005','1006');
INSERT INTO "orden_produccion" VALUES(NULL,
		'non, hendrerit id, ante. Nunc',
		'1005',
		31,
		'1004',
		'1000',
		'01/16/11',
		'1005',
		'01/09/12',
		'et arcu imperdiet ullamcorper.',
		'Duis dignissim tempor arcu. Vestibulum',
		'1003',
		'1004');
INSERT INTO "orden_produccion" VALUES(NULL,
		'in aliquet lobortis, nisi nibh',
		'1002',
		25,
		'1001',
		'1003',
		'07/25/11',
		'1003',
		'02/22/12',
		'eu metus. In lorem.','vitae, sodales at, velit. Pellentesque',
		'1005',
		'1002');
INSERT INTO "orden_produccion" VALUES(NULL,
		'nec tempus mauris erat eget',
		'1000',
		13,
		'1005',
		'1003',
		'08/12/12',
		'1006',
		'09/26/12',
		'mi felis, adipiscing fringilla,',
		'semper pretium neque. Morbi quis',
		'1002',
		'1002');

INSERT INTO "proveedor" VALUES(NULL,
		'Callum Lynn',
		'(494)764-8882',
		'544-886 Gravida Ave',
		'mus.Aenean@Maurismolestiepharetra.edu');
INSERT INTO "proveedor" VALUES(NULL,
		'Andrew Campbell',
		'(926)247-3963',
		'897-1094 Placerat. Ave',
		'egestas@velquamdignissim.edu');
INSERT INTO "proveedor" VALUES(NULL,
		'Mannix Dickson',
		'(290)234-9774',
		'4888 Tincidunt St.',
		'torquent.per.conubia@ultriciesornare.ca');
INSERT INTO "proveedor" VALUES(NULL,
		'Magee Scott',
		'(504)308-2655',
		'2588 Luctus Avenue',
		'ligula.Aenean.gravida@enimnisl.org');
INSERT INTO "proveedor" VALUES(NULL,
		'Palmer Mcmahon',
		'(795)608-0191',
		'P.O. Box 661',
		' 9978 Ultrices Road urna.Nunc@arcu.com');
INSERT INTO "proveedor" VALUES(NULL,
		'Nolan Mullins',
		'(891)947-8053',
		'2522 Ut Road',
		'Etiam.imperdiet@diamluctuslobortis.com');
INSERT INTO "proveedor" VALUES(NULL,
		'Jordan Harper',
		'(809)474-7135',
		'P.O. Box 911',
		' 9508 Pharetra St.massa.Suspendisse.eleifend@Suspendisse.org');
INSERT INTO "proveedor" VALUES(NULL,
		'Moses Leon',
		'(556)520-3269',
		'8750 Venenatis Ave',
		'Fusce@vitaesodales.com');
INSERT INTO "proveedor" VALUES(NULL,
		'Tanner Long',
		'(441)812-7296',
		'415-7515 Ut Rd.',
		'nonummy.Fusce.fermentum@acmattis.com');
INSERT INTO "proveedor" VALUES(NULL,
		'Kenyon Cotton',
		'(708)742-7709',
		' P.O. Box 770 4467 Duis St.',
		'ut.nisi.a@pedenecante.edu');
INSERT INTO "proveedor" VALUES(NULL,
		'Marvin Reese',
		'(526)300-0391',
		'Ap #321-7396 Non St.',
		'elit@Aliquam.ca');
INSERT INTO "proveedor" VALUES(NULL,
		'Jamal Estrada',
		'(230)362-8293',
		'Ap #659-6529 Dapibus St.',
		'ipsum.Phasellus.vitae@Proindolor.org');
----------------------------------------------------------------------
INSERT INTO "tecnico" VALUES(NULL,
		'Hayden Clemons',
		'(877)280-2647',
		'Ap #892-2742 Nulla Rd.',
		'nunc@nonarcuVivamus.edu',
		'habitant');
INSERT INTO "tecnico" VALUES(NULL,
		'Yuli Vincent',
		'(329)608-5946',
		'Ap #241-9727 Fermentum St.Curae',
		'Donec.tincidunt@nunc.edu','lorem');
INSERT INTO "tecnico" VALUES(NULL,
		'Vaughan Russell',
		'(804)625-0919',
		'6213 Diam St.',
		'Quisque@ametultriciessem.com',
		'tellus');
INSERT INTO "tecnico" VALUES(NULL,
		'Colorado Moss',
		'(884)531-5292',
		'P.O. Box 156 8921 Per Avenue',
		'eget.tincidunt@Fuscealiquetmagna.org',
		'Mauris');
INSERT INTO "tecnico" VALUES(NULL,
		'Lars Hogan',
		'(409)148-2173',
		'8894 Penatibus Rd.',
		'metus@rhoncus.org',
		'dui');
INSERT INTO "tecnico" VALUES(NULL,
		'Gary Porter',
		'(207)752-9791',
		'652-8772 Adipiscing Rd.',
		'adipiscing.non@dignissimmagnaa.com',
		'facilisis');
INSERT INTO "tecnico" VALUES(NULL,
		'Deacon Harmon',
		'(311)301-8673',
		'P.O. Box 509 4552 Amet Road',
		'quam@tincidunt.edu',
		'Cum');
INSERT INTO "tecnico" VALUES(NULL,
		'Addison Salazar',
		'(451)725-2119',
		'7019 Tristique Road',
		'magna.a.neque@egestas.ca',
		'Aenean');
INSERT INTO "tecnico" VALUES(NULL,
		'Ian Mcleod',
		'(157)411-3133',
		'Ap #139-6362 Phasellus Av.',
		'pellentesque@eu.org',
		'porttitor');
INSERT INTO "tecnico" VALUES(NULL,
		'Amos Gregory',
		'(250)731-8874',
		'4068 Velit Avenue',
		'mi.lacinia@urnasuscipitnonummy.ca',
		'enim');
-----------------------------------------------------------------------------------------------------------
INSERT INTO "insumo" VALUES(NULL,
		644,
		307,
		790,
		'04/01/11',
		'dolor dapibus gravida. Aliquam tincidunt,',
		140,
		'ac sem',
		'Nullam',
		'dolor. Fusce',
		'Mauris blandit enim consequat',
		'15/09/12',
		'1004',
		'721');
INSERT INTO "insumo" VALUES(NULL,
		562,
		558,
		810,
		'02/05/12',
		'Morbi accumsan laoreet ipsum. Curabitur',
		106,
		'turpis vitae',
		'inceptos',
		'sed orci',
		'et, lacinia vitae, sodales',
		'05/06/12',
		'1005',
		'916');
INSERT INTO "insumo" VALUES(NULL,
		561,
		930,
		796,
		'04/06/11',
		'mi lacinia mattis. Integer eu',
		128,
		'dis parturient',
		'id',
		'fermentum convallis',
		'lectus pede et risus.',
		'24/07/12',
		'1004',
		'541');
INSERT INTO "insumo" VALUES(NULL,
		420,
		585,
		379,
		'11/27/12',
		'nonummy ac, feugiat non, lobortis',
		123,
		'purus mauris',
		'accumsan',
		'libero est,',
		'ipsum dolor sit amet,',
		'11/10/11',
		'1003',
		'540');
INSERT INTO "insumo" VALUES(NULL,
		832,
		168,
		673,
		'12/31/10',
		'egestas blandit. Nam nulla magna,',
		109,
		'dolor quam,',
		'ornare',
		'lorem, vehicula',
		'elit, pellentesque a, facilisis',
		'14/10/12',
		'1006',
		'178');
INSERT INTO "cliente" VALUES(NULL,
		'Kasper Sandoval',
		'(653)968-2110',
		'8631 Eu Ave',
		'Donec.consectetuer@et.ca');
INSERT INTO "cliente" VALUES(NULL,
		'Jonah Murray',
		'(958)499-6594',
		'1896 Magna. St.',
		'Etiam.vestibulum@ornaretortor.ca');
INSERT INTO "cliente" VALUES(NULL,
		'Drew Grimes',
		'(197)506-0693',
		'Ap #642-8486 Ante Road',
		'lobortis.mauris@laoreetposuere.com');
INSERT INTO "cliente" VALUES(NULL,
		'Damon Noel',
		'(802)586-0477',
		'306-1477 Ac Rd.',
		'turpis.Aliquam@ullamcorpereueuismod.edu');
INSERT INTO "cliente" VALUES(NULL,
		'Logan Orr',
		'(420)338-5694',
		'315-8981 Enim Ave',
		'at@leo.com');
INSERT INTO "cliente" VALUES(NULL,
		'Hop Stuart',
		'(270)219-7438',
		'7895 Nullam St.',
		'aliquet.molestie.tellus@erat.org');
INSERT INTO "cliente" VALUES(NULL,
		'Tanner Griffith',
		'(196)770-5322',
		'964-5927 Vel Rd.',
		'eu.eros@mieleifendegestas.com');
INSERT INTO "cliente" VALUES(NULL,
		'Colby Roth',
		'(483)301-1847',
		'8877 Eros. Rd.',
		'ante.Vivamus.non@lectusante.ca');
INSERT INTO "cliente" VALUES(NULL,
		'Chadwick Erickson',
		'(222)978-0493',
		'P.O. Box 658 6024 At Av.',
		'Donec.consectetuer.mauris@rutrum.ca');
INSERT INTO "cliente" VALUES(NULL,
		'Connor Clay',
		'(727)347-2179',
		'879-3842 Interdum. Rd.',
		'nisi.sem@dapibusgravida.org');


----------------------------------------------
INSERT INTO "producto_terminado" VALUES(NULL,
		'1002',
		'diam dictum sapien. Aenean',
		14,
		'1004',
		'1002',
		'ornare',
		'mollis.',
		'faucibus lectus, a sollicitudin',
		'1002',
		'05/15/12',
		'1002',
		'12/21/12',
		'1006',
		'lacinia at, iaculis quis, pede. Praesent');
INSERT INTO "producto_terminado" VALUES(NULL,
		'1000',
		'nascetur ridiculus mus. Donec',
		10,
		'1003',
		'1003',
		'arcu',
		'rhoncus.',
		'diam eu dolor egestas',
		'1001',
		'06/21/12',
		'1006',
		'11/17/12',
		'1001',
		'Integer in magna. Phasellus dolor elit,');
INSERT INTO "producto_terminado" VALUES(NULL,
		'1006',
		'hendrerit a, arcu. Sed',
		10,
		'1003',
		'1006',
		'non,',
		'metus',
		'non lorem vitae odio',
		'1005',
		'12/14/11',
		'1003',
		'07/05/11',
		'1005',
		'Nunc ullamcorper, velit in aliquet lobortis,');
INSERT INTO "producto_terminado" VALUES(NULL,
		'1006',
		'vestibulum nec, euismod in,',
		18,
		'1004',
		'1005',
		'nec,',
		'Mauris',
		'pharetra, felis eget varius',
		'1002',
		'01/04/11',
		'1003',
		'11/29/12',
		'1005',
		'convallis ligula. Donec luctus aliquet odio.');
INSERT INTO "producto_terminado" VALUES(NULL,
		'1006',
		'et netus et malesuada',
		3,
		'1003',
		'1001',
		'mollis',
		'a',
		'lorem fringilla ornare placerat,',
		'1003',
		'05/14/11',
		'1005',
		'04/16/11',
		'1002',
		'fermentum metus. Aenean sed pede nec');
COMMIT;
